### ISSUE TITLE
can't "go get" the repo

### ISSUE THREAD

**Issue by broady** [cel-expr/cel-go#53] opened 2018-08-13 20:53 UTC
```
$ go get -u github.com/google/cel-go/...
package github.com/google/cel-spec/proto/checked/v1/checked: cannot find package "github.com/google/cel-spec/proto/checked/v1/checked" in any of:
	/usr/local/google/home/cbro/go/src/github.com/google/cel-spec/proto/checked/v1/checked (from $GOROOT)
	/usr/local/google/home/cbro/src/github.com/google/cel-spec/proto/checked/v1/checked (from $GOPATH)
package github.com/google/cel-spec/proto/v1/syntax: cannot find package "github.com/google/cel-spec/proto/v1/syntax" in any of:
	/usr/local/google/home/cbro/go/src/github.com/google/cel-spec/proto/v1/syntax (from $GOROOT)
	/usr/local/google/home/cbro/src/github.com/google/cel-spec/proto/v1/syntax (from $GOPATH)
package github.com/google/cel-go/server: found packages main (main.go) and server (server.go) in /usr/local/google/home/cbro/src/github.com/google/cel-go/server
```

Related to #51.

I know Bazel has appeal, but if it's getting in the way of Go developers actually using the package, something is wrong.

**Comment by TristonianJones** [comment] 2018-08-14 22:11
I believe this is a duplicate of issue #51. Bazel is used to link against protos which are defined in the https://github.com/google/cel-spec repo. We're working on moving away from relying on `cel-spec` as part of the `BUILD`, but have a bunch of cleanup work to do.

We'll make sure to make this easier to use for Go developers in the next quarter. Thanks for the feedback!

**Closed as completed** 2018-08-14 22:12 UTC
Labels: duplicate
