### ISSUE TITLE
Calling ListType Overloads with mixed types incorrectly compile & match invalid overload

### ISSUE THREAD

**Issue by davidjb** [cel-expr/cel-go#660] opened 2023-03-14 04:59 UTC
**Describe the bug**
Declaring a function with an overload that accepts a List of any given type (String, Int, Double, etc) results in CEL code successfully compiling where mixed list element types are used. For example, the example below is a function called `max([...])` which takes a List of Ints. When trying to call `max()` with a list of doubles, it fails with:

    found no matching overload for 'max' applied to '(list(double))'

However, when called with a mixture of types, such as `max(['a', 'b', 1.3])`, code successfully compiles with the chekcer resolving the `max_int` overload regardless of the mixture of types.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [x]  checker
- [ ]  interpreter

Sample expression and input that reproduces the issue:
```cel
max([1, 1.1])
max([1, 'a', 1.1])
```

Test setup:
```go
import (
	exprpb "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
)

func TestMixedListTypes(t *testing.T) {
	env, err := cel.NewEnv(cel.Declarations(
		decls.NewFunction("max", decls.NewOverload("max_int", []*exprpb.Type{decls.NewListType(decls.Int)}, decls.Int)),
	))
	if err != nil {
		panic(err)
	}

	_, issues := env.Compile("max([1.1, 2.1])")
	if len(issues.Errors()) != 0 {
		t.Log("Issues detected with non-int, type-matched elements: ", issues.String())
		// issues.String() outputted below
	}

	_, issues = env.Compile(`max([1, 2, 3])`)
	if len(issues.Errors()) == 0 {
		t.Log("No issues detected with consistent types that match the overload")
	}

	_, issues = env.Compile("max(['a', 1.1])")
	if len(issues.Errors()) == 0 {
		t.Error("No issues detected with mixed, unrelated types")
	}
}
```

**Expected behavior**
Overload to not match and to yield a `noMatchingOverload` error like the following which occurs when trying to compile `max([1.1, 2.1])` with a list of doubles, when it's set to accept a list of ints.

```go
ERROR: <input>:1:4: found no matching overload for 'max' applied to '(list(double))'
         | max([1.1, 2.1])
         | ...^
```

**Additional context**
Tested with the latest `master` version (https://github.com/google/cel-go/commit/af2e9432d89762934a75772bc0d84fd8fdbe2c6d) at time of writing, and also with the current release version v0.13.0 and behaviour is the same.

**Comment by TristonianJones** [comment] 2023-03-14 05:11
@davidjb when there's a list of mixed type, the element type gets marked as `list(dyn)` which means that type-checking will defer to runtime to determine whether there's an overload that can be found. In other words, you'll see an error, just much later.

The behavior you're seeing is working as intended; however, there's an option you might want to consider which will help: `cel.HomogeneousAggregateLiterals()` If you enable this option in your environment, the type-checker will reject mixed type lists and you you'll consistently get the right behavior.

**Closed as completed by TristonianJones** 2023-03-14 05:11 UTC

**Comment by davidjb** [comment] 2023-03-14 05:34
Super, thanks very much for the quick response @TristonianJones. The function works exactly as you've said - thanks for the pointer. Just a slight note for anyone reading this later: the function is `cel.HomogeneousAggregateLiterals()` (an extra `e` was needed in homogeneous). Thanks again 👍

**Comment by TristonianJones** [comment] 2023-03-14 05:50
Thanks, I corrected the reference. I'm glad that helped.
